[package]
name = "dev-shell"
version = "0.0.1"
edition = "2021"
authors = ["Graham Brooks<graham@grahambrooks.com>"]
description = "A command line shell for using GenerativeAI tools in the command line"
readme = "README.md"
repository = "https://github.com/grahambrooks/dev-shell"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
serde = { version = "1.0.68", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.28.2", features = ["full"] }
futures = { version = "0.3.28" }
clap = { version = "4.3.8", features = ["derive"] }
reqwest = { version = "0.11", features = ["stream", "blocking", "json"] }
tera = "1.19.0"
os_info = "3.7.0"
termion = "2.0.1"
