[workspace]
members = [
    "openai"
]

[package]
name = "dev-shell"
version = "0.0.3"
build = "build.rs"
edition = "2021"
authors = ["Graham Brooks<graham@grahambrooks.com>"]
description = "A command line shell for using GenerativeAI tools in the command line"
readme = "README.md"
repository = "https://github.com/grahambrooks/dev-shell"
license = "MIT"

[[bin]]
name = "dev-shell"
path = "src/main.rs"

[dependencies]
openai = { path = "openai" }
hyper = { version = "0.14", features = ["full"] }
include_dir = "0.7.3"
os_info = "3.7.0"
atty = "0.2.14"
serde = { version = "1.0.68", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.28.2", features = ["full"] }
futures = { version = "0.3.28" }
clap = { version = "4.3.8", features = ["derive"] }
reqwest = { version = "0.11", features = ["stream", "blocking", "json"] }
tera = "1.19.0"
termion = "2.0.1"
mime_guess = { version = "2.0.4", features = [] }
tokio-tungstenite = "0.20.1"
async-openai = "0.16.0"
