[package]
name = "dev-shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version="1.28.2", features = ["full"] }
futures = { version = "0.3.28" }
clap = { version = "4.3.8", features = ["derive"] }
reqwest = { version = "0.11", features = ["stream", "blocking", "json"] }