site_name: Genie GenAI Documentation
site_author: graham@grahambrooks.com
site_description: Genie GenAI Documentation
docs_dir: doc
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Command line:
      - Run: run-command.md
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search